"""Published vendor examples: constants transcribed from source, never generated by our solver."""

from dataclasses import replace

from rf_link_calculator.domain.codec import hashes
from rf_link_calculator.domain.models import Analysis, Mixer, NoiseSpec, PowerSpec, Project, Stage

LOW_IF_URL = "https://www.mathworks.com/help/rf/ug/rf-budget-harmonic-balance-analysis-of-low-if-receiver-ip2-and-nf.html"
IP3_URL = "https://www.mathworks.com/help/rf/ref/rfbudget.html"


def attach_reference(project, expected, url, scope_note):
    keys = ("gain_db", "nf_db", "iip3_dbm", "linear_output_dbm", "frequency_output_hz")
    units = ("dB", "dB", "dBm", "dBm", "Hz")
    rows = []
    for scope, values in [(s.id, v) for s, v in zip(project.stages, expected)] + [("chain", expected[-1])]:
        for key, unit, value in zip(keys, units, values):
            rows.append(
                {
                    "scope": scope,
                    "metric": key,
                    "value": "" if value is None else str(value),
                    "unit": unit,
                    "status": "ideal" if value is None else "valid",
                }
            )
    lab = {
        "models": {},
        "settings": {},
        "reference": {
            "kind": "reference",
            "rows": rows,
            "metadata": {
                "software": "MathWorks RF Toolbox",
                "version": "公开文档快照 2026-09-23；页面未标注运行版本",
                "solver": "Friis",
                "source": "published",
                "url": url,
                "scope": scope_note,
                "calculation_hash": hashes(project)[1],
                "rounding_tolerance_db": 0.001,
            },
        },
    }
    return replace(project, schema_version="2.0.0", lab=lab)


def examples():
    low_if = Project(
        project_id="published-mathworks-low-if-friis",
        project_name="MathWorks 公开算例",
        link_name="公开算例 · Friis 下变频",
        analysis=Analysis(
            source_frequency_hz=2.1e9, input_power_dbm=-30, signal_bandwidth_hz=45e6, noise_bandwidth_hz=45e6
        ),
        stages=tuple(
            Stage(
                id=f"mathworks-low-if-{i}",
                order=i,
                name=name,
                type=kind,
                gain_db=gain,
                noise=NoiseSpec("manual", nf),
                ip3=PowerSpec("ideal"),
                mixer=Mixer(lo_frequency_hz=2.03e9, noise_convention="SSB", noise_compatible=True)
                if kind == "mixer"
                else None,
                source={
                    "kind": "published",
                    "url": LOW_IF_URL,
                    "note": "Friis 参考口径；不模拟文档中的 IP2 与 HB 噪声折叠",
                },
            )
            for i, (name, kind, gain, nf) in enumerate(
                (
                    ("RFAmplifier", "amplifier", 11.53, 1.53),
                    ("Demodulator", "mixer", -6, 4),
                    ("IFAmplifier", "amplifier", 30, 8),
                ),
                1,
            )
        ),
        notes="只验收文档中的 Friis 五项预算；不包含其 HB/IP2 结果；本机未运行 MATLAB。",
    )
    low_if = attach_reference(
        low_if,
        [
            (11.53, 1.53, None, -18.47, 2.1e9),
            (5.53, 1.843, None, -24.47, 70e6),
            (35.53, 4.793, None, 5.53, 70e6),
        ],
        LOW_IF_URL,
        "完整三器件 Friis 链路；五项预算，NF 按文档 0.001 dB 显示精度比较",
    )
    ip3 = Project(
        project_id="published-mathworks-ip3-prefix",
        project_name="MathWorks 公开算例",
        link_name="公开算例 · IP3 级联",
        analysis=Analysis(
            source_frequency_hz=2.1e9, input_power_dbm=-30, signal_bandwidth_hz=10e6, noise_bandwidth_hz=10e6
        ),
        stages=(
            Stage(
                id="mathworks-ip3-1",
                name="Amplifier",
                gain_db=4,
                noise=NoiseSpec("ideal"),
                ip3=PowerSpec("ideal"),
            ),
            Stage(
                id="mathworks-ip3-2",
                order=2,
                name="Modulator",
                type="mixer",
                gain_db=0,
                noise=NoiseSpec("ideal"),
                ip3=PowerSpec("finite", "output", 13),
                mixer=Mixer(
                    lo_frequency_hz=1e9, relation="sum", noise_convention="SSB", noise_compatible=True
                ),
            ),
            Stage(
                id="mathworks-ip3-3",
                order=3,
                name="RFElement",
                gain_db=10,
                noise=NoiseSpec("ideal"),
                ip3=PowerSpec("ideal"),
            ),
        ),
        notes="原文四级链路的前三个 Friis 前缀；未获取第四级 passive.s2p，未推测其网络；本机未运行 MATLAB。",
    )
    ip3 = attach_reference(
        ip3,
        [(4, 0, None, -26, 2.1e9), (4, 0, 9, -26, 3.1e9), (14, 0, 9, -16, 3.1e9)],
        IP3_URL,
        "原文第一个算例的前三个 Friis 前缀；不包含第四级 passive.s2p",
    )
    return {p.link_name: p for p in (low_if, ip3)}
