TYPES = {
    "lna": "低噪声放大器",
    "amplifier": "放大器",
    "pa": "功率放大器",
    "vga": "可变增益放大器",
    "filter_bpf": "带通滤波器",
    "filter_lpf": "低通滤波器",
    "filter_hpf": "高通滤波器",
    "filter_bsf": "带阻滤波器",
    "attenuator": "衰减器",
    "cable": "电缆",
    "connector": "连接损耗",
    "switch": "开关",
    "isolator": "隔离器",
    "mixer": "混频器",
    "coupler": "耦合器",
    "splitter": "功分器",
    "custom": "自定义模型",
    "input": "输入边界",
    "output": "输出边界",
    "antenna": "天线边界",
    "adc": "ADC标注边界",
    "dac": "DAC标注边界",
    "digital": "数字标注边界",
}
BOUNDARIES = {"input", "output", "antenna", "adc", "dac", "digital"}
PASSIVE = {
    "filter_bpf",
    "filter_lpf",
    "filter_hpf",
    "filter_bsf",
    "attenuator",
    "cable",
    "connector",
    "switch",
    "isolator",
    "coupler",
    "splitter",
}
LINK_TYPES = {
    "receiver": "接收",
    "transmitter": "发射",
    "upconverter": "上变频",
    "downconverter": "下变频",
    "other": "其他",
}
STATUS = {
    "valid": "有效",
    "estimated": "模型估算",
    "unknown": "未知／参数不完整",
    "ideal": "理想／无有限值",
    "not_applicable": "不适用",
    "invalid": "输入无效",
    "failed": "计算失败",
}
NOISE = {"unknown": "未知", "manual": "手动NF", "passive_thermal": "热无源", "ideal": "理想无噪声"}
POWER = {"unknown": "未知", "finite": "有限值", "ideal": "理想线性"}
P1REF = {"input": "输入", "actual_output": "实际输出", "linear_output": "线性外推输出"}
IP3REF = {"input": "输入", "output": "输出"}
METRICS = {
    "gain_db": ("总增益", "dB"),
    "linear_output_dbm": ("线性输出功率", "dBm"),
    "nf_db": ("级联噪声系数", "dB"),
    "te_k": ("等效输入附加噪声温度", "K"),
    "noise_input_dbm": ("输入参考噪声", "dBm"),
    "noise_output_dbm": ("输出噪声", "dBm"),
    "snr_db": ("线性输出信噪比", "dB"),
    "iip3_dbm": ("系统IIP3", "dBm"),
    "oip3_dbm": ("系统OIP3", "dBm"),
    "ip1_dbm": ("系统输入P1（模型估算）", "dBm"),
    "op1_dbm": ("系统实际输出P1（模型估算）", "dBm"),
    "compressed_output_dbm": ("当前压缩输出（模型估算）", "dBm"),
    "compression_db": ("当前总压缩（模型估算）", "dB"),
    "sensitivity_dbm": ("输入灵敏度", "dBm"),
    "compression_dr_db": ("P1回退约束输入动态范围（估算）", "dB"),
    "sfdr3_db": ("SFDR3（指定噪声带宽）", "dB"),
    "sfdr3_normalized": ("SFDR3（1 Hz归一化）", "dB·Hz^(2/3)"),
    "tone_limit_dbm": ("IM3等于噪声的每音输入上限", "dBm"),
    "tone_span_db": ("满足指定SNR的双音可用跨度", "dB"),
    "tone_input_dbm": ("双音每音输入", "dBm"),
    "tone_total_dbm": ("双音总平均输入", "dBm"),
    "tone_output_dbm": ("每音线性输出", "dBm"),
    "im3_dbm": ("每个IM3分量输出", "dBm"),
    "im3_dbc": ("IM3相对每音基波", "dBc"),
    "frequency_output_hz": ("输出中心频率", "Hz"),
}
